In [6]:
import uproot
import pandas as pd
import numpy as np

In [7]:
cd ..

/global/u2/s/schuya

In [8]:
from visualization.hcal import Event

In [9]:
root_dir = uproot.rootio.open('/global/cscratch1/sd/schuya/hgcal-dev/data/hcal/data.root')
root_events = root_dir.get('Events;1')

In [10]:
df = pd.DataFrame()
for k, v in root_events[b'HcalRecHit'].items():
    df[k.decode('ascii').split('.')[1]] = v.array()

In [12]:
events = []
for n in range(df.shape[0]):
    jagged_event = df.loc[n]
    df_dict = {k: jagged_event[k] for k in jagged_event.keys()}
    flat_event = pd.DataFrame(df_dict)
    flat_event.astype({'hit': int})
    events.append(Event(flat_event))

In [15]:
events[0].df

,fUniqueID,fBits,energy,timeFalling,time,x,y,z,hit
0,0,50331648,0.000000,-120.0,-9999.000000,176.761093,39.186989,-7.878279,0
1,0,50331648,0.000000,-120.0,-9999.000000,152.698349,97.279587,-7.878279,0
2,0,50331648,0.000000,-120.0,-9999.000000,69.285896,167.270950,-7.878280,0
3,0,50331648,0.000000,-120.0,-9999.000000,39.186996,176.761093,-7.878280,0
4,0,50331648,0.000000,-120.0,-9999.000000,7.897408,180.880447,-7.878280,0
...,...,...,...,...,...,...,...,...,...
797,0,50331648,0.000000,-100.0,-9999.000000,116.903458,54.512974,522.797974,1
798,0,50331648,0.335638,-100.0,6.058261,105.661339,73.984886,522.797974,1
799,0,50331648,3.172715,7.0,9.654989,91.569252,64.117477,522.797974,1
800,0,50331648,0.000000,-100.0,-9999.000000,87.946541,-7.694312,487.997986,1
801,0,50331648,0.523764,-100.0,12.500000,77.473808,54.247746,522.797974,1

In [18]:
len(events)

10010

In [19]:
from pathlib import Path

In [20]:
data_path = Path('/global/cscratch1/sd/schuya/hgcal-dev/data/hcal')
event_path = data_path / 'event_0.pkl'

In [22]:
events[0].df.to_pickle(event_path)

In [23]:
events[0].df

,fUniqueID,fBits,energy,timeFalling,time,x,y,z,hit
0,0,50331648,0.000000,-120.0,-9999.000000,176.761093,39.186989,-7.878279,0
1,0,50331648,0.000000,-120.0,-9999.000000,152.698349,97.279587,-7.878279,0
2,0,50331648,0.000000,-120.0,-9999.000000,69.285896,167.270950,-7.878280,0
3,0,50331648,0.000000,-120.0,-9999.000000,39.186996,176.761093,-7.878280,0
4,0,50331648,0.000000,-120.0,-9999.000000,7.897408,180.880447,-7.878280,0
...,...,...,...,...,...,...,...,...,...
797,0,50331648,0.000000,-100.0,-9999.000000,116.903458,54.512974,522.797974,1
798,0,50331648,0.335638,-100.0,6.058261,105.661339,73.984886,522.797974,1
799,0,50331648,3.172715,7.0,9.654989,91.569252,64.117477,522.797974,1
800,0,50331648,0.000000,-100.0,-9999.000000,87.946541,-7.694312,487.997986,1
801,0,50331648,0.523764,-100.0,12.500000,77.473808,54.247746,522.797974,1

In [24]:
events[0].df[['x', 'y', 'z']].values

array([[176.7611   ,  39.18699  ,  -7.878279 ],
       [152.69835  ,  97.27959  ,  -7.8782787],
       [ 69.2859   , 167.27095  ,  -7.8782797],
       ...,
       [ 91.56925  ,  64.11748  , 522.798    ],
       [ 87.94654  ,  -7.6943116, 487.998    ],
       [ 77.47381  ,  54.247746 , 522.798    ]], dtype=float32)